seed: 42
device: cuda
num_steps_per_env: 24
max_iterations: 10000
empirical_normalization: false
policy:
  class_name: ActorCriticRecurrent
  init_noise_std: 1.0
  actor_hidden_dims:
  - 512
  - 256
  - 128
  critic_hidden_dims:
  - 512
  - 256
  - 128
  activation: elu
  rnn_type: lstm
  rnn_hidden_size: 512
  rnn_num_layers: 1
algorithm:
  class_name: PPO
  value_loss_coef: 1.0
  use_clipped_value_loss: true
  clip_param: 0.2
  entropy_coef: 0.01
  num_learning_epochs: 5
  num_mini_batches: 4
  learning_rate: 0.001
  schedule: adaptive
  gamma: 0.99
  lam: 0.95
  desired_kl: 0.01
  max_grad_norm: 1.0
save_interval: 100
experiment_name: unitree_go2_vel_custom
run_name: ''
logger: tensorboard
neptune_project: orbit
wandb_project: orbit
resume: false
load_run: .*
load_checkpoint: model_.*.pt
